# These data will be shown in /about page and every page footer
# Replace these with your own personal info

name: "Claus Prüfer"
job: "CTO / Developer"
hi: "Welcome to my IT-Blog!"
avatar_img: "/assets/img/me.png" # path to your avatar
intro:
  - "Im Laufe meiner Karriere habe ich umfassende Erfahrungen in der Umsetzung unterschiedlichster IT-Projekte gesammelt – von kleinen Anwendungen über komplexe Enterprise-Lösungen bis hin zu Carrier-Grade-Infrastrukturen."
  - "Seit den frühen Tagen der agilen Entwicklungstheorie, über Virtualisierungs- und Loadbalancer-Technologien, Software-Defined Networking und bis zu den jüngsten Innovationen rund um Google Kubernetes, habe ich die IT-Landschaft seit dem Jahr 2000 intensiv und kritisch begleitet."
  - "„Nomen est Omen“ – mein Nachname „Prüfer“ hat mich dabei oft in herausfordernde Situationen geführt. Das Prüfen und Hinterfragen liegt mir im Blut; es fällt mir schlichtweg schwer, Themen nicht einer gründlichen Analyse zu unterziehen."
  - "Genau deshalb habe ich mich entschieden, ab sofort regelmäßig aktuelle IT-Trends und Technologien als „IT-Prüfer“ auf Der-IT-Pruefer.de zu beleuchten und meine Erfahrungen mit Euch zu teilen."
  - "Viel Spaß beim Lesen!"
skills:
  - name: "Programming"
    icon-class: "fa fa-terminal"
    list: ["Python", "JavaScript", "C++", "Shell", "SQL", "XML", "JSON"]
  - name: "Framework"
    icon-class: "fa fa-th-list"
    list: ["x0 (Cross-Objects)", "Google Kubernetes"]
  - name: "Tools"
    icon-class: "fa fa-cogs"
    list: ["Linux", "Docker", "Git", "libvirt", "Latex"]

display_name: "CLAUS PRÜFER"
contact:
  - {name: "Mobile", icon-class: "fa fa-phone-square", text: "+49 (30) 33 60 7177", link: "tel: 0493033607177"}
  - {name: "Email", icon-class: "fa fa-envelope", text: "info@der-it-pruefer.de", link: "mailto: info@der-it-pruefer.de"}
  - {name: "Internet", icon-class: "fa fa-link", text: "http://www.webcodex.de", link: "http://www.webcodex.de"}
social:
  - {name: "GitHub", icon-class: "fa fa-github-square", text: "https://github.com/clauspruefer", link: "https://github.com/clauspruefer"}
  - {name: "Xing", icon-class: "fa fa-xing", text: "https://www.xing.com/profile/Claus_Pruefer", link: "https://www.xing.com/profile/Claus_Pruefer"}
